repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: dts
    url: https://helm.dts-stn.com    
#context: WATP

#default values to set for args along with dedicated keys that can be set by contributers, cli args take precedence over these
helmDefaults:
  verify: false
  wait: false

environments:
    watp:

releases:


# Deliverables


  - name: traefik-watp
    chart: stable/traefik
    namespace: ingress-{{ .Environment.Name }}
    version: 1.87.2
    values:
      - charts/traefik/prod.yaml.gotmpl
    labels:
        category: ingress
        app: traefik
    wait: false
    installed: true
    force: false

  - name: watp
    chart: dtsweb/dts-web
    version: 0.0.3
    namespace: watp
    values:
      - charts/watp/prod.yaml.gotmpl    
    labels:
        category: watp
        app: home
    wait: false
    installed: true
    force: false


